format_version: 2
#=========================================================
# Common environment variables
#=========================================================
common:
  default_region: &region
    REGION: 'ap-southeast-2'
  docker_repo: &docker_repo
    DOCKER_REPO: 'docker-env.artifacts.tabdigital.com.au'
  default_environment_variables: &default_environment_variables
    <<: *docker_repo
    <<: *region

#=========================================================
#  GoCD Environment definitions
#=========================================================
environments:
  uat-yarra: #  UAT Yarra
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'UAT-Yarra'
      AWS_PROFILE: 'test'
#=========================================================
  uat-murray: # UAT Murray
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'UAT-Murray'
      AWS_PROFILE: 'test'
#=========================================================
  preproduction: #  PreProduction
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'PreProduction'
      AWS_PROFILE: 'test'
#=========================================================
  production:
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'Production'
      AWS_PROFILE: 'test'
#=========================================================
  tools:
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'Tools'
      AWS_PROFILE: 'test'
#=========================================================
  tools-production: &tools-production
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'Tools-Production'
      AWS_PROFILE: 'test'
   pipelines:
      - go-Agent-EC2
#=========================================================
  productiondr:
    environment_variables:
      <<: *docker_repo
      REGION: 'ap-northeast-1'
      ENVIRONMENT: 'ProductionDR'
      AWS_PROFILE: 'test'
pipelines:
 #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../pipeline/Go-Agent-EC2/production.yaml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# go-Agent-EC2-yaml.yml
  "go-Agent-EC2":
    group: tools-production
    << : *tools-production
    materials:
      Deployment:
       git: git@github.tabcorp.com.au:TabDigital/deployment.git
       branch: master
       destination: deployment
    parameters: # list of parameters that can be configured for a pipeline
      app_home: tools/apps/go-agents-ec2   
    template: DeployEC2_CI
