
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../environments/environments.yaml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

format_version: 2
#=========================================================
# Common environment variables
#=========================================================
common:
  default_region: &region
    REGION: 'ap-southeast-2'
  docker_repo: &docker_repo
    DOCKER_REPO: 'docker-env.artifacts.tabdigital.com.au'
  default_environment_variables: &default_environment_variables
    <<: *docker_repo
    <<: *region

#=========================================================
#  GoCD Environment definitions
#=========================================================
environments:
  uat-yarra:  &uat-yarra #  UAT Yarra
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'UAT-Yarra'
      AWS_PROFILE: 'test'
#=========================================================
  uat-murray: &uat-murray  # UAT Murray
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'UAT-Murray'
      AWS_PROFILE: 'test'
#=========================================================
  preproduction: &preproduction #  PreProduction
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'PreProduction'
      AWS_PROFILE: 'test'
#=========================================================
  production: &production
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'Production'
      AWS_PROFILE: 'test'
#=========================================================
  tools: &tools
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'Tools'
      AWS_PROFILE: 'test'
#=========================================================
  productiondr: &productiondr
    environment_variables:
      <<: *docker_repo
      REGION: 'ap-northeast-1'
      ENVIRONMENT: 'ProductionDR'
      AWS_PROFILE: 'test'
pipelines:
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../pipeline/service-multiplier/preproduction.yaml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# service-multiplier-preproduction.yml
  "service-multiplier-preproduction":
    group: group1
    << : *preproduction
    materials:
      Deployment:
       git: git@github.tabcorp.com.au:TabDigital/deployment.git
       branch: master
       destination: dir-preproduction1
      service-multiplier:
       git: git@github.tabcorp.com.au:TabDigital/deployment-trigger.git 
       destination: dir-preproduction2     
    template: test-template1
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../pipeline/service-multiplier/production.yaml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# service-multiplier-production.yml
  "service-multiplier-production":
    group: group1
    << : *production
    materials:
      Deployment:
       git: git@github.tabcorp.com.au:TabDigital/deployment.git
       branch: master
       destination: dir-prod1
      service-multiplier:
       git: git@github.tabcorp.com.au:TabDigital/deployment-trigger.git 
       destination: dir-prod2     
    template: test-template1
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../pipeline/service-multiplier/uat-murray.yaml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# service-multiplier-yarra.yml
  "service-multiplier-murray":
    group: group1
    << : *uat-murray
    materials:
      Deployment:
       git: git@github.tabcorp.com.au:TabDigital/deployment.git
       branch: master
       destination: dir-murray1     
      service-multiplier:      
       git: git@github.tabcorp.com.au:TabDigital/deployment-trigger.git
       destination: dir-murray2
    template: test-template1
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../pipeline/service-multiplier/uat-yarra.yaml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# service-multiplier-yarra.yml
  "service-multiplier-yarra":
    group: group1
    << : *uat-yarra
    materials:
      Deployment:
       git: git@github.tabcorp.com.au:TabDigital/deployment.git
       branch: master
       destination: dir-yarra1     
      service-multiplier:      
       git: git@github.tabcorp.com.au:TabDigital/deployment-trigger.git
       destination: dir-yarra2
    template: test-template1
