
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../environments/environments.yaml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

format_version: 2
#=========================================================
# Common environment variables
#=========================================================
common:
  default_region: &region
    REGION: 'ap-southeast-2'
  docker_repo: &docker_repo
    DOCKER_REPO: 'docker-env.artifacts.tabdigital.com.au'
  default_environment_variables: &default_environment_variables
    <<: *docker_repo
    <<: *region

#=========================================================
#  GoCD Environment definitions
#=========================================================
environments:
  uat-yarra:  &uat-yarra #  UAT Yarra
    environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'UAT-Yarra'
      AWS_PROFILE: 'test'
#=========================================================
  uat-murray: &uat-murray  # UAT Murray
    # environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'UAT-Murray'
      AWS_PROFILE: 'test'
#=========================================================
  preproduction: &preproduction #  PreProduction
    # environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'PreProduction'
      AWS_PROFILE: 'test'
#=========================================================
  production: &production
    # environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'Production'
      AWS_PROFILE: 'test'
#=========================================================
  tools: &tools
    # environment_variables:
      <<: *default_environment_variables
      ENVIRONMENT: 'Tools'
      AWS_PROFILE: 'test'
#=========================================================
  productiondr: &productiondr
    # environment_variables:
      <<: *docker_repo
      REGION: 'ap-northeast-1'
      ENVIRONMENT: 'ProductionDR'
      AWS_PROFILE: 'test'

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../pipeline/service-multiplier/production.yml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# service-multiplier-production.yml
production-pipeline: &production-pipeline
  service-multiplier-production:
    group: group1
    environment_variables:
      DEPLOYMENT: testing
      FOO: bar
      << : *production
    materials:
      Deployment:
       git: git@github.tabcorp.com.au:TabDigital/deployment.git
       branch: feature12
       destination: dir-prod1
      service-multiplier:
       git: git@github.tabcorp.com.au:TabDigital/deployment-trigger.git 
       destination: dir-prod2     
    template: test-template1
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../pipeline/service-multiplier/uat-murray.yml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# service-multiplier-yarra.yml
murray-pipeline: &murray-pipeline
  service-multiplier-murray:
    group: group1
    environment_variables:
      DEPLOYMENT: testing
      FOO: bar
      << : *uat-murray
    materials:
      Deployment:
       git: git@github.tabcorp.com.au:TabDigital/deployment.git
       branch: feature12
       destination: dir-murray1     
      service-multiplier:      
       git: git@github.tabcorp.com.au:TabDigital/deployment-trigger.git
       destination: dir-murray2
    template: test-template1

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../pipeline/service-multiplier/pipelines.yml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

pipelines:
  <<: *production-pipeline
  <<: *murray-pipeline
